import { Router } from 'express';
import { makeCrud } from '../crud.js';
const r = Router();
const crud = makeCrud('customers');
r.get('/', crud.list);
r.get('/:id', crud.get);
r.post('/', crud.create);
r.put('/:id', crud.update);
r.delete('/:id', crud.remove);
export default r;
